### ISSUE TITLE
windows helpers: `python3` command doesn't work

### ISSUE THREAD

**Issue by silphendio** [adosikas/synth_mapping_helper#4]
This is about the .bat files:
At least in Windows 11, `python3` just shows python in the app store.
`python` or `py` work

**Comment by adosikas** [comment]
This is unfortunately an issue when python is not installed from the Windows Store.  
"Easy" solution is to uninstall python from the Windows Store and any other Python installations and install from Windows Store again.

You can also turn of the "helpful" aliases via some Windows menu, see https://stackoverflow.com/questions/58754860/cmd-opens-windows-store-when-i-type-python

**Comment by adosikas** [comment]
`python` seemed to work just as well, so I changed the windows tools to that. I doubt anyone will be installing Python 2 these days...
